web:
    build: .
    ports:
      - "443:5000"
    volumes:
      - ./app:/code/app
    command: python ./app/app.py
    links:
      - db

db:
    hostname: mysqlserver
    image: mysql:5.7.20 #mariadb:latest
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vacation
      MYSQL_USER: user
      MYSQL_PASSWORD: password

adminer:
    image: adminer
    container_name: adminer
    restart: always
    links:
     - db
    ports:
      - "8080:8080"