version: '3.3'
services:
  web:
    build: .
    ports:
     #- "80:5000"
      - "443:5000"
    volumes:
      - ./app:/code/app
    command: python ./app/app.py
    depends_on:
      - db

  db:
    image: mysql:5.7.20
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vacation
      #MYSQL_USER: wordpress
      #MYSQL_PASSWORD: wordpress

  adminer:
    image: adminer:4.3.1
    restart: always
    ports:
      - 8080:8080

volumes:
    db_data: